package:
  name: attrdict
  version: "2.0.0"

source:
  fn: attrdict-2.0.0.tar.gz
  url: https://files.pythonhosted.org/packages/35/bb/bac3e42ae04bc082c28cd8186bfb5b50fb240a4f7419f876c683125ccc8b/attrdict-2.0.0.tar.gz
  md5: 8a7c1a4e737fe9e2b2b8844c0f7746f8
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - attrdict = attrdict:main
    #
    # Would create an entry point called attrdict that calls attrdict.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - six

  run:
    - python
    - six

test:
  # Python imports
  imports:
    - attrdict

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - coverage
    - nose >=1.0
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/bcj/AttrDict
  license: MIT License
  summary: 'A dict with attribute-style access'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
