"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ["bin/explore-qualities"]
DATA_FILES = ['bin/explore-qualities', 'gaussian3d-1e4.hdf5', "settings.ini", "settings_classes.ini", "rave-test.hdf5"]
OPTIONS = {'argv_emulation': True}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    includes=["mayavi", "gavi", "h5py.defs"],
    #packages=["h5py"]
)
