name: "Copy dlls for windows"
description: "Copy dlls for windows"
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        ls /c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2019/Enterprise/VC/Redist/
        ls /c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2019/Enterprise/VC/Redist/MSVC/
        cp /c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2019/Enterprise/VC/Redist/MSVC/14.29.30133/x64/Microsoft.VC142.CRT/vcruntime140_1.dll packages/vaex-core/vaex/
        mkdir packages/vaex-core/vendor/pcre
        cd packages/vaex-core/vendor/pcre
        curl https://anaconda.org/conda-forge/pcre/8.44/download/win-64/pcre-8.44-h6538335_0.tar.bz2 -Lo pcre.tar.bz2
        tar jxfv pcre.tar.bz2
        cd ../../
        cp vendor/pcre/Library/bin/*.dll vaex/
        cd ../../
