version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    parameters:
      python-version:
        type: string
    executor:
      name: win/default
      size: "medium"
      shell: bash.exe

    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run:
          name: Set up conda
          command: |
            conda config --set always_yes yes --set changeps1 no
            conda update -q conda
            conda install -y -q -c conda-forge mamba --quiet
      - run:
          name: Create vaex-dex environment
          command: |
            mamba create -y -q -c conda-forge -n vaex-dev python=<< parameters.python-version >> compilers --file ci/conda-env.yml
            source activate vaex-dev
            conda list
      - run:
          name: Install vaex
          command: |
            source activate vaex-dev
            conda list
            pip install -e .
      - run:
          name: Run all tests
          command: |
            source activate vaex-dev
            set VAEX_SERVER_OVERRIDE={"dataframe.vaex.io":"dataframe-dev.vaex.io"}
            python -m vaex.test.dataset TestDataset
            py.test tests/ --timeout=1000


workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          matrix:
            parameters:
              python-version: ["3.7", "3.8", "3.9"]