name: vaex-dev
channels:
  - msys2
  - conda-forge
  - pkgs/main
  - numba/label/dev
dependencies:
- astropy
- cython
- cachetools
- catboost
- compilers
- diskcache
- fsspec <0.9
- gcsfs
- geopandas
- graphviz
- h5py
- ipyvolume=0.6.0a6
- lightgbm
- matplotlib-base
- nbconvert=6.1.0
- notebook
- numba
- numpy<1.21
- pandas
- pcre
- pip
- plotly
- python-annoy
- pyarrow
- pyqt
- pytest
- pytest-asyncio<0.14
- pytest-mpl
- pytest-timeout
- python-graphviz
- s3fs
- scikit-learn
- scipy
- pkgs/main::tensorflow>=2.0.0
- tornado
- xarray
- pip:
  - myst_parser