name: vaex-dev
channels:
  - msys2
  - conda-forge
  - pkgs/main
  - numba/label/dev
dependencies:
- astropy
- cython
- cachetools
- catboost
- diskcache
- fsspec
- gcsfs
- geopandas
- graphviz
- h5py
- ipyvolume=0.6.0a6
- lightgbm
- matplotlib-base
- notebook
- numba
- numpy<1.21
- pandas
- pcre
- pip
- plotly
- python-annoy
- pyarrow>=4.0.0
- pyqt
- pytest
- pytest-asyncio<0.14
- pytest-mpl
- pytest-timeout
- python-graphviz
- py-xgboost
- s3fs>=2021.8.0
- scikit-learn
- scipy
- tornado
- xarray
- pip:
  - myst_parser
  - tensorflow==2.6.0
  - keras==2.6.0
