name: vaex-dev
channels:
  - msys2
  - conda-forge
  - numba/label/dev
dependencies:
- aplus
- astropy
- blake3
- cython
- cachetools
- catboost
- diskcache
- fsspec<2022.2.0
- gcsfs
- geopandas
- graphviz
- h5py
- httpx # for testing with starlette/fastapi
- ipyvolume=0.6.0a6
- lightgbm
- matplotlib-base
- nest-asyncio<1.5.2
- notebook
- numba
- numpy
- pandas
- pcre
- pip==20.3.4
- plotly
- python-annoy
- pyarrow>=5.0.0
- pyqt
- pytest
- pytest-asyncio
- pytest-mpl
- pytest-timeout
- python-graphviz
- py-xgboost
- rich
- s3fs>=2021.8.0
- scikit-learn
- scipy
- tornado
- uvicorn<0.16
- xarray<2022.6.0
# currently not using this, since the test that requires this is flakey
# - myst-parser<0.18  # 0.18 breaks our test, missing main
