name: Python package

on:
  push:
    branches:
    - release
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 10
      matrix:
        os: [windows-latest]
        python-version: [3.6, 3.7]

    steps:
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        toolset: 14.0
    - name: 'debug'
      shell: bash
      run: |
        ls /c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2019/Enterprise
        find /c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2019 -iname 'vcvarsall.bat'
        /c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2019/Enterprise/VC/Auxiliary/Build/vcvarsall.bat x86_amd64 -vcvars_ver=14.0
    - name: 'debug2'
      shell: cmd
      run: |
        call "c:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat" -vcvars_ver=14.0
        echo %VCToolsInstallDir%
    - uses: actions/checkout@v1
      with:
        submodules: true
    # - name: Install conda with Python ${{ matrix.python-version }}
    #   uses: s-weigand/setup-conda@master
    #   with:
    #     python-version: ${{ matrix.python-version }}
    #     conda-channels: anaconda, conda-forge
    - uses: goanpeca/setup-miniconda@v1
      with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
    - name: Create env
      # if: steps.cache-conda-env.outputs.cache-hit != 'true'
      run: |
        conda create -q -n vaex -c conda-forge python=${{ matrix.python-version }} pip wheel pcre
    # - name: Add conda to path
    #   shell: bash
    #   run: |
    #     conda init --all
    #     echo ::add-path::$CONDA/envs/vaex/bin
    - name: Fix python-dateutil/botocore version conflict
      shell: cmd
      run: |
        conda activate vaex
        pip install python-dateutil==2.8.0  # botocore caps dateutil leading to issues
    - name: Cache compiled binaries
      id: cache-compiled-binaries
      uses: actions/cache@v1
      with:
        path: packages/vaex-core/build
        key: ${{ runner.OS }}-${{ matrix.python-version }}-${{ hashFiles('packages/vaex-core/src/*') }}
    # - name: Fix cache timestamp
    #   # if: steps.cache-compiled-binaries.outputs.cache-hit == 'true' && matrix.os != 'windows-latest'
    #   shell: bash
    #   run: |
    #     find packages/vaex-core/build -type f -exec touch {} +
    - name: Create binary wheel
      shell: cmd
      run: >-
        conda activate vaex &&
        cd packages/vaex-core &&
        call "c:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat" -vcvars_ver=14.0 &&
        python setup.py bdist_wheel
    - name: Upload wheel
      uses: actions/upload-artifact@v1
      with:
        name: vaex-core-${{ matrix.python-version }}
        path: packages/vaex-core/dist
    - name: Install vaex-core
      shell: cmd
      run: >-
        conda activate vaex &&
        pip install packages/vaex-core/dist/*.whl
    - name: Test import
      shell: cmd
      run: >-
        conda activate vaex &&
        python -c 'import vaex; df = vaex.from_scalars(x=1, y=2); print(df)'
